[package]
name = "server"
version = "0.1.0"
edition = "2024"

[dependencies]
axum = {version="0.8.1", features=["macros"]}
chrono = "0.4.40"
serde = "1.0.219"
sha2 = "0.10.8"
sqlx = {version="0.8.3", features=["postgres", "runtime-tokio-native-tls"]}
tokio = {version="1.0", features=["full"]}
