[package]
name = "server"
version = "0.1.0"
edition = "2024"

[dependencies]
axum = {version="0.8.1", features=["macros"]}
sqlx = "0.8.3"
tokio = {version="1.44.1", features=["postgres", "runtime-tokio-native-tls"]}
